/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRadioSplatRouteImport } from './routes/api/public/radio.$'
import { Route as ApiPublicHlsSplatRouteImport } from './routes/api/public/hls.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRadioSplatRoute = ApiPublicRadioSplatRouteImport.update({
  id: '/api/public/radio/$',
  path: '/api/public/radio/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHlsSplatRoute = ApiPublicHlsSplatRouteImport.update({
  id: '/api/public/hls/$',
  path: '/api/public/hls/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/hls/$': typeof ApiPublicHlsSplatRoute
  '/api/public/radio/$': typeof ApiPublicRadioSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/hls/$': typeof ApiPublicHlsSplatRoute
  '/api/public/radio/$': typeof ApiPublicRadioSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/hls/$': typeof ApiPublicHlsSplatRoute
  '/api/public/radio/$': typeof ApiPublicRadioSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/hls/$' | '/api/public/radio/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/hls/$' | '/api/public/radio/$'
  id: '__root__' | '/' | '/api/public/hls/$' | '/api/public/radio/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicHlsSplatRoute: typeof ApiPublicHlsSplatRoute
  ApiPublicRadioSplatRoute: typeof ApiPublicRadioSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/radio/$': {
      id: '/api/public/radio/$'
      path: '/api/public/radio/$'
      fullPath: '/api/public/radio/$'
      preLoaderRoute: typeof ApiPublicRadioSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hls/$': {
      id: '/api/public/hls/$'
      path: '/api/public/hls/$'
      fullPath: '/api/public/hls/$'
      preLoaderRoute: typeof ApiPublicHlsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicHlsSplatRoute: ApiPublicHlsSplatRoute,
  ApiPublicRadioSplatRoute: ApiPublicRadioSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
